spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:9999
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0
#  cloud:
#    gateway:
#      discovery.locator:
#        enabled: true
#        lower-case-service-id: true

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
