spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:9999
  profiles:
    active: dev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:currencyExchange
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9000

test:
  hello: hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka


resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s
