spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/MustafaSmesem/microservice/blob/master/git-local-config-repo/

server:
  port: 9999
