spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: file:///Users/mustafatanitek/development/projects/microservices/complete/microservice/git-local-config-repo

server:
  port: 9999
