spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:9999
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9100


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
